### ISSUE TITLE
Bib file formatting not support

### ISSUE THREAD

**Issue by RohanAsmat** [vkaravir/bib-publication-list#18]
Does my bib needs to be in particular format to get the output ?
Following error is thrown when I provide as an input the complete bib file but when I just provide three to four selective content elements they generate accurate table.

```
bib-list-min.js:284 Uncaught TypeError: this.raiseError is not a function
    at BibTex._determineCase (bib-list-min.js:284)
    at BibTex._extractAuthors (bib-list-min.js:276)
    at BibTex._parseEntry (bib-list-min.js:253)
    at BibTex.parse (bib-list-min.js:230)
    at Bib2HTML.initialize (bib-list-min.js:369)
    at new Bib2HTML (bib-list-min.js:369)
    at bib-list-min.js:382
    at 127.0.0.1/:237
```

**Comment by RohanAsmat** [comment]
Well I noticed the problem was with comma separated author list instead of and's, but I think this is one of the errors. Following is the link to a similar bibsonomy:

https://www.bibsonomy.org/bib/user/aksw

You can check this one out, please let me know if you can figure out the exact trouble.

**Comment by vkaravir** [comment]
I fixed quite a few issues and the bibtex from the bibsonomy link works now. Let me know if you still have issues with your bibtex.

**Comment by RohanAsmat** [comment]
The update fixed quite a number of issues. 

but I still find this one issue, for captial letters in the tittle attribute for example the following:

`title= {{SampleResearch}: Open Research for Scientists}`

The parser throws an error, would be happy if you can manage to fix this one too.

**Comment by vkaravir** [comment]
This does work for me. But if I don't have the comma like in your example, I do get an error. I fixed that now so that it won't crash. But the title will still be missing as the bibtex is invalid (assuming of course that title isn't the last line for the entry). If it still won't work for you, could you share the whole entry with the issue?

Also, I changed it so that the whole code shouldn't crash if displaying one of the entries fails. But if the parser fails, everything still fails.

**Comment by chsu5358** [comment]
For bibtex files that list authors in the format used by Google Scholar, ex: "author={last_name1, first_name1 and last_name2, first_name2 and last_name3, first_name3}," it seems to display only the last names in the rendered table instead of displaying full name in the order of "first_name last_name" (such as that in your personal website example.) 
Can we switch to displaying full names for the author field? Or do we need to manually change the author field in bibtex files to "author={first_name1 last_name1 and first_name2 last_name2 and first_name3 last_name3}"?

**Comment by vkaravir** [comment]
Good catch @chsu5358! I just pushed a fix for it, let me know if you still have the issue.
