### ISSUE TITLE
Fail to parse Editor in Book Chapter

### ISSUE THREAD

**Issue by renzomassobrio** [vkaravir/bib-publication-list#21]
Hello, 

There seems to be an error when parsing Editors of a book chapter. 
If the "inbook" entry type is used the editor appears as "object Object".
If the "incollection" entry type is used instead, then the editor field is simply ignored and the entry is categorized as "Misc".

See the MWEs below.
Thanks for your support!

bib:
@inbook{doe2017,
  author = {John Doe},
  editor = {Jane Doe},
  chapter  = {Chapter title},
  publisher = {The publisher},
  title={Book title},
  year = {2017},
  pages={1-3}
}

Output:
John Doe (2017). Chapter title in Book title, Edited by [object Object], The publisher, pp. 1-3.

bib:
@incollection{doe2017,
  author = {John Doe},
  editor = {Jane Doe},
  chapter  = {Chapter title},
  publisher = {The publisher},
  title={Book title},
  year = {2017},
  pages={1-3}
}

Output:
John Doe (2017). Book title.

**Comment by vkaravir** [comment]
Thanks for reporting! These should now be fixed, although the in collection entry doesn't use all the possible fields. Also, for you example it will show the book title as missing since I believe the book title should be in the book title field, and the title of the work in title. Pull requests are welcome to improve this :)

Thanks again!
